[build]
  command = "npm run build --prefix frontend"
  publish = "frontend/build"

[functions]
  directory = "functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
